#!/bin/bash

# 4K display scaling on *Tokyo*
wlr-randr | grep 4K | awk '{print $1}' |
while IFS= read DISPLAY; do
	$(wlr-randr --output $DISPLAY --scale 1.5)
done

wlr-randr --output DP-3 --pos 2560,0

# 1080p display scaling on laptops
if [[ $(cat /etc/hostname) == kyoto ]] || [[ $(cat /etc/hostname) == nagoya ]]; then
	$(wlr-randr --output eDP-1 --scale 1.25)
fi
