#!/bin/bash

TOUCHPAD=$(riverctl list-inputs | grep Synaptics)
if [ ! -z "$TOUCHPAD" ]; then
	riverctl input $TOUCHPAD accel-profile adaptive
	riverctl input $TOUCHPAD pointer-accel 0.8
	riverctl input $TOUCHPAD natural-scroll enabled
	riverctl input $TOUCHPAD tap enabled
fi

